/*
   Copyright (c) 2016 by Plexim GmbH
   All rights reserved.

   A free license is granted to anyone to use this software for any legal
   non safety-critical purpose, including commercial applications, provided
   that:
   1) IT IS NOT USED TO DIRECTLY OR INDIRECTLY COMPETE WITH PLEXIM, and
   2) THIS COPYRIGHT NOTICE IS PRESERVED in its entirety.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.
 */

#ifndef SETTINGS_H_
#define SETTINGS_H_

#include "|>BASE_NAME<|.h"

#include "settings.inc"

#define LSPCLK_HZ (SYSCLK_HZ / 4l)

#define TASK2_HZ |>TASK2_HZ<|
#define DOUT_PS_ENABLE_GPIO |>DOUT_PS_ENABLE_GPIO<|

#define CONTROL_TS |>BASE_NAME<|_sampleTime
#define CONTROL_STEP |>BASE_NAME<|_step()
#define CONTROL_INIT |>BASE_NAME<|_initialize(0.0)

#endif /* SETTINGS_H_ */
